# this is run in all zsh sessions, interactive or not, login or not

if [[ -f $HOME/.shenv ]] ; then source $HOME/.shenv ; fi

# ZSH specific environment
DEBIAN_PREVENT_KEYBOARD_CHANGES=yes

if test -d ${HOME}/.local/bin ; then
  export PATH="${HOME}/.local/bin:${PATH}"
fi

if [[ ! -o interactive ]]; then
  if command -v mise 2>/dev/null ; then
    eval "$(mise activate zsh --shims)"
  fi
fi
