tap "dart-lang/dart"
tap "holtwick/tap"
tap "sass/sass"


brew "ack"
brew "acme.sh"
brew "age"
brew "autoconf"
brew "automake"
brew "b2-tools"
brew "bat"
brew "binwalk"
brew "cask"
brew "ccache"
brew "certbot"
brew "cloudflared"
brew "cmake"
brew "colima"
brew "devcontainer"
brew "dfu-util"
brew "difftastic"
brew "direnv"
brew "duck"
brew "earthly"
brew "esptool"
brew "fish"
brew "gh"
brew "ghidra", link: false
brew "git"
brew "git-delta"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "gradle"
brew "hf"
brew "holtwick/tap/bx"
brew "htop"
brew "httpie"
brew "hugo"
brew "imagemagick"
brew "john-jumbo"
brew "jq"
brew "kubeconform"
brew "kubectx"
brew "librsvg"
brew "lima"
brew "minikube"
brew "mise"
brew "mosh"
brew "neovim"
brew "ninja"
brew "nmap"
brew "ollama"
brew "p7zip"
brew "pipenv"
brew "pipx"
brew "pkgconf"
brew "protobuf"
brew "pwgen"
brew "pwntools"
brew "qemu"
brew "restic"
brew "ripgrep"
brew "ruby"
brew "ruby@3.3"
brew "rustup"
brew "sass/sass/migrator"
brew "sass/sass/sass"
brew "shellcheck"
brew "smartmontools"
brew "starship"
brew "tmux"
brew "uv"
brew "virtualenvwrapper"
brew "wget"
brew "yt-dlp"
brew "zlib"
brew "zsh-syntax-highlighting"


cask "codeql"
cask "cyberduck"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-go-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-symbols-only-nerd-font"
cask "font-terminess-ttf-nerd-font"
cask "ghidra"
cask "github"
cask "iterm2"
cask "keybase"
cask "macfuse"
cask "meld"
cask "mitmproxy"
cask "processmonitor"
cask "raycast"
cask "rectangle"
cask "scroll-reverser"
cask "temurin"
cask "veracrypt"
cask "wezterm"
cask "zulu@17"

def is_corp?
  # Check for MDM enrollment (Enrolled via DEP: Yes)
  `profiles status -type enrollment 2>/dev/null`.include?("Enrolled via DEP: Yes")
end

if is_corp?
  brew "bazelisk", link: false
end

# non-corp
if !is_corp?
  brew "bazelisk"
  brew "openssh"
  cask "claude-code"
  cask "cryptomator"
  cask "gcloud-cli"
  cask "google-cloud-sdk"
  cask "orbstack"
end
